### ISSUE TITLE
Test was run double

### ISSUE THREAD

**Issue by gigkokman** [lukaszb/nose-watch#14]
I'm create a simple test (fizzbuzz) and run nose with nose-watch option. My test run double.

#### System information ####
argh (0.26.1)
nose (1.3.7)
nose-watch (0.9.1)
pathtools (0.1.2)
pip (1.5.6)
PyYAML (3.11)
setuptools (3.6)
watchdog (0.8.3)
wsgiref (0.1.2)

#### Example code #####
https://github.com/gigkokman/fizzbuzz.git

#### Result ####
```.
----------------------------------------------------------------------
Ran 1 test in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK```

**Comment by rsdenijs** [comment]
I assume it is due to that multiple files are edited when you save? E.g.,  a .swp file?

**Comment by gigkokman** [comment]
I think you are right, @rsdenijs, because I've used vim.
thx, :+1:
